### ISSUE TITLE
Callback wouldn't fire

### ISSUE THREAD

**Issue by zcsongor** [erunion/showtimes#27]
Hi!

There is no response at all, I did not get anything back from the callback. Is it just me?

Ps.: trying with latlong, 's' object looks okay.

Thanks!

**Comment by erunion** [comment]
Can you send me the location you're using?

**Comment by zcsongor** [comment]
'47.473973, 19.047646'
Now I got answer, which is undefined.

**Comment by erunion** [comment]
I'm having trouble replicating this. Can you paste your Showtimes implementation?

**Comment by zcsongor** [comment]
```javascript
var showtimes = require('showtimes');
var s = showtimes('47.473973, 19.047646', {});

app.controller('appController', ['$scope', '$q', '$filter', '$state', function ($scope, $q, $filter, $state) {
    s.getTheaters(function (err, theaters) {
        console.log(theaters);
     });
}]);
```

**Comment by erunion** [comment]
Ah, hmm. The library is completely untested in a browser environment.  Can you log `err` and see if that's throwing an error back?

**Comment by zcsongor** [comment]
Ah, yeah, now I got the error message: "TypeError: Failed to execute 'fetch' on 'Window': Failed to parse URL from //google.com:80/movies?hl=en&near=47.473973%2C%2019.047646&date=0&start=0"

**Comment by erunion** [comment]
Awesome, I'll take a look this evening and see if I can figure out what the problem is.

**Comment by erunion** [comment]
@zcsongor Sorry, I have zero experience with Cordova. You mind either sharing the app you have, or instructions for how you're getting Showtimes into it?
