### ISSUE TITLE
Don't submit ES6 source to npm - compile first, and only publish ES5 code

### ISSUE THREAD

**Issue by stevus** [erunion/showtimes#39]
Put this in your `package.json` which will auto-compile/transpile your code before publishing to NPM:

```
"scripts": {
    "compile": "babel -d lib/ src/",
    "prepublish": "npm run compile"
},
```

This way, I don't need to transpile your module to use it in my project. You would just publish as normal:

```
npm publish ./
```

**Comment by erunion** [comment]
I think I'm going to close this out. I only really want to support Node 4.x going forward, since that has ES6 support.
