### ISSUE TITLE
Theater id not being parsed from cloaked URL properly

### ISSUE THREAD

**Issue by jmathai** [erunion/showtimes#43]
The following line always returns false.

```
        cloakedUrl = qs.parse(url.parse(cloakedUrl))
```

We need to parse the `query` attribute of the hash returned by `url.parse`.

```
        cloakedUrl = qs.parse(url.parse(cloakedUrl).query)
```

**Comment by erunion** [comment]
Hey! Can you submit a PR for this? Looks like you already fixed it in your fork.

**Comment by erunion** [comment]
Nevermind, just saw your PR!

**Comment by erunion** [comment]
Merged your PR. Thanks for the fix!
