### ISSUE TITLE
Documentation of how to use those file

### ISSUE THREAD

**Issue by KennyJack** [erunion/showtimes#45]
Hi,

May i know how to use or implement movies.js, theaters.js file? There are no instruction on how to use it. it would be great if you can provide them @erunion

**Comment by erunion** [comment]
Unfortunately you can't use `movies.js` and `theaters.js` by themsevles. If you want to use the showtimes library, you have to use the whole library on a server.

Showtimes cannot currently be used within a web browser.

**Comment by erunion** [comment]
Yes, the library makes a cURL request to Google Movies to scrape and aggregate data.

For setting it up on a server, it really depends on what you're application is doing. You could have an AJAX request that sends a call to something like `/getMovies?location=11011`. For your backend server (the handler for the `/getMovies` AJAX request), you'll have to have some sort of [NodeJS](https://nodejs.org) server running to use this. Using a Node framework like [Express](http://expressjs.com/) might make your life easier getting up and running.

Once you have that all up and running, you can use [NPM](https://www.npmjs.com/) to install the library.

Then in your Express framework code, you can use the library within a request handler like:

```
var Showtimes = require('showtimes');
var api = new Showtimes(<`location` GET parameter>, {});

api.getTheaters(function (error, theaters) {
  if (error) {
    throw error
  }

  <return a response of `theaters`>
});
```
